### ISSUE TITLE
Validation metrics for labelled unseen data. 

### ISSUE THREAD

**Issue by uramith** [talegari/tidyrules#20]
Additional functionalities for validation on an unseen data set. This will enable end users to get more confidence on the shortlisted rules and from the model explainability point of view as well good to have.

**Comment by talegari** [comment]
@uramith You will be implementing this (`augment`)

**Comment by talegari** [comment]
https://github.com/talegari/tidyrules/pull/29/commits/da13066363857513cd9106311eaa978a469cb18e
